server:
  port: 8090

# 分组任务配置
chatbot-api:
  launchList: group01 # 启动几组，就配置几组 group01,group02
  group01:
    groupName: 飞铸股权
    groupId: 28885428428851 # 知识星球ID
    cookie:  zsxq_access_token=522D3DB2-85CE-F9E5-0381-F97CA21D58AA_6D186878CD2C1117; sensorsdata2015jssdkcross=%7B%22distinct_id%22%3A%22185888812214122%22%2C%22first_id%22%3A%22188b972fb8c224-026c55b65d1605-26031d51-2073600-188b972fb8df4a%22%2C%22props%22%3A%7B%22%24latest_traffic_source_type%22%3A%22%E7%9B%B4%E6%8E%A5%E6%B5%81%E9%87%8F%22%2C%22%24latest_search_keyword%22%3A%22%E6%9C%AA%E5%8F%96%E5%88%B0%E5%80%BC_%E7%9B%B4%E6%8E%A5%E6%89%93%E5%BC%80%22%2C%22%24latest_referrer%22%3A%22%22%7D%2C%22%24device_id%22%3A%22188b972fb8c224-026c55b65d1605-26031d51-2073600-188b972fb8df4a%22%2C%22identities%22%3A%22eyIkaWRlbnRpdHlfY29va2llX2lkIjoiMTg4Yjk3MzRkNDBiN2UtMDA2MjM0MWNlZmEyYmFmNC0yNjAzMWQ1MS0yMDczNjAwLTE4OGI5NzM0ZDQxZjFmIiwiJGlkZW50aXR5X2xvZ2luX2lkIjoiMTg1ODg4ODEyMjE0MTIyIn0%3D%22%2C%22history_login_id%22%3A%7B%22name%22%3A%22%24identity_login_id%22%2C%22value%22%3A%22185888812214122%22%7D%7D; zsxqsessionid=e744e634fecd51bed2e8ca2aa8f67cdf; abtest_env=product # 知识星球个人cookie信息
    openAiKey:  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 # 自行申请 https://beta.openai.com/overview 或者联系小傅哥 fustack 付费申请【购买虚拟号码等需要支付】。
    cronExpression: 0/30 * * * * ? # 执行的频次配置，参考：cron.qqe2.com
    silenced: false
  group02:
    groupName: xxx
    groupId: 28885518425541 # 知识星球ID
    cookie:  # 知识星球个人cookie信息
    openAiKey:  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 # 自行申请 https://beta.openai.com/overview 或者联系小傅哥 fustack 付费申请【购买虚拟号码等需要支付】。
    cronExpression: 0/30 * * * * ? # 执行的频次配置，参考：cron.qqe2.com
    silenced: true